version: "2.4"
services:
    simulator:
        container_name: wifi_simulator
        build: .
        volumes:
            - ./cache:/home/genie/app/cache:rw
        environment:
            - WIFI_USER=${WIFI_USER}
            - WIFI_PW=${WIFI_PW}
            - WIFI_HOST=wifi_db
            - WIFI_PORT=5432
        tty: true
        cpus: 20
        cpuset: 1-20
        mem_limit: 100Gb
        stdin_open: true
        restart: always

networks:
    default:
        external: true
        name: cofi_bridge

